export enum ProjectPosition {
  BACKEND = "BACKEND",
  FRONTEND = "FRONTEND",
  FULLSTACK = "FULLSTACK",
  QA = "QA",
  DEVOPS = "DEVOPS",
  MOBILE = "MOBILE",
  UI_UX = "UI_UX",
  PRODUCT_MANAGER = "PRODUCT_MANAGER",
  DATA = "DATA",
  SECURITY = "SECURITY",
  ARCHITECT = "ARCHITECT"
}
