

export enum ActivityType {
    CONNECTED = "CONNECTED",
    SENT_JOIN_REQUEST = "SENT_JOIN_REQUEST",
    SENT_CONNECTION_REQUEST = "SENT_CONNECTION_REQUEST",
    JOINED_PROJECT = "JOINED_PROJECT",
    CREATED_PROJECT = "CREATED_PROJECT",
    CREATED_POST = "CREATED_POST",
    DELETE_POST = "DELETE_POST",
    DELETED_PROJECT = "DELETED_PROJECT",
}